jadwalku/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.addschedule, name='addschedule'),
    path('save/', views.saveschedule, name='saveschedule'),
    path('delete_all/', views.delete_all, name='delete_all'),
]

story9/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('google-apis-json-books/', views.google_apis_books, name='google-apis-books'),
    path('fav/', views.fav, name='fav'),
    path('unfav/', views.unfav, name='unfav'),
]

websiteku/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profilku.urls')),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('schedule/', include(('jadwalku.urls', 'jadwalku'), namespace='jadwalku')),
    path('story9/', include(('story9.urls', 'story9'), namespace="story9")),
    path('subscribe/', include(('subscribe.urls', 'subscribe'), namespace="subscribe")),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here
]

jadwalku/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):
    date = models.DateField(null=True)
    time = models.TimeField(null=True)
    name = models.CharField(max_length=200)
    place = models.CharField(max_length=200)
    category = models.CharField(max_length=200)

    def __str__(self):
        return self.name

jadwalku/forms.py
from django import forms

class Schedule_Form(forms.Form):
    error_messages = {
        'required': 'Please type',
    }
    date_attrs = {
        'type': 'date',
        'placeholder':'Date'
    }
    time_attrs = {
        'type': 'time',
        'placeholder': 'Time'
    }
    name_attrs = {
        'type': 'text',
        'placeholder':'Name'
    }
    place_attrs = {
        'type': 'text',
        'placeholder':'Place'
    }
    category_attrs = {
        'type': 'text',
        'placeholder':'Category'
    }

    date = forms.DateField(label='', required=True, widget=forms.DateInput(attrs=date_attrs))
    time = forms.TimeField(label='', required=True, widget=forms.TimeInput(attrs=time_attrs, format='%H:%M'))
    name = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=name_attrs))
    place = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=place_attrs))
    category = forms.CharField(label='', required=True, widget=forms.TextInput(attrs=category_attrs))

jadwalku/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Schedule_Form
from .models import Schedule

response = {}


# Create your views here.
def index(request):
    schedule = Schedule.objects.all()
    response['schedule'] = schedule
    response['title'] = 'My Schedule'

    html = 'jadwalku/index.html'
    return render(request, html, response)


def addschedule(request):
    response['schedule_form'] = Schedule_Form
    response['title'] = 'Add Schedule'

    html = 'jadwalku/add.html'

    return render(request, html, response)


def saveschedule(request):
    form = Schedule_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        response['date'] = request.POST['date']
        response['time'] = request.POST['time']
        response['name'] = request.POST['name']
        response['place'] = request.POST['place']
        response['category'] = request.POST['category']
        schedule = Schedule(date=response['date'], time=response['time'], name=response['name'],
                            place=response['place'], category=response['category'])
        schedule.save()
        return HttpResponseRedirect('/schedule/')
    else:
        return HttpResponseRedirect('/schedule/')


def delete_all(request):
    Schedule.objects.all().delete()
    schedule = Schedule.objects.all()
    response['schedule'] = schedule
    response['title'] = 'My Schedule'
    return render(request, 'jadwalku/index.html', response)

templates/jadwalku/add.html
{% extends "profilku/head.html" %}
{% load staticfiles %}
{% block content %}
<div class="grid-container">
  <div class="grid-x grid-margin-x align-center-middle text-center">
    <div class="cell medium-12 title">Add Schedule</div>
  </div>
</div>
<div class="grid-x">
  <div class="cell medium-12 card">
    <form class="grid-x grid-margin-x register" action="{% url 'jadwalku:saveschedule' %}" method="POST">
      {% csrf_token %}
      <div class="cell medium-6">
        <label>Date:
          {{schedule_form.date}}
        </label>
      </div>
      <div class="cell medium-6">
        <label>Time:
          {{schedule_form.time}}
        </label>
      </div>
      <div class="cell medium-6">
        <label>Name:
          {{schedule_form.name}}
        </label>
      </div>
      <div class="cell medium-6">
        <label>Place:
          {{schedule_form.place}}
        </label>
      </div>
      <div class="cell medium-6">
        <label>Category:
          {{schedule_form.category}}
        </label>
      </div>
      <div class="cell grid-x align-right">
        <div class="cell medium-3 text-right">
          <input type="submit" class="button" value="Submit">
        </div>
      </div>
  </form>
</div>
{% endblock %}

templates/jadwalku/index.html
{% extends "profilku/head.html" %}
{% load staticfiles %}
{% block content %}
    <div class="grid-container">
      <div class="grid-x grid-margin-x align-middle text-center">
        <div class="cell medium-12 title">My Schedule</div>
      </div>
      <div class="cell grid-x align-right">
        <div class="cell medium-3 text-right">
          <a href="{% url 'jadwalku:delete_all' %}">
            <button type="button" class="button" name="button">Delete All</button>
          </a>
        </div>
      </div>
    </div>
    <div class="grid-x align-center-middle">
      {% for data in schedule %}
      <div class="cell medium-4 text-center">
        <h2>{{data.name}}</h2>
        <h6>Date: {{data.date}}</h6>
        <h6>Time: {{data.time}}</h6>
        <p>Place: {{data.place}}</p>
        <p>Category: {{data.category}}</p>
      </div>
      {% endfor %}
    </div>
{% endblock %}